export enum RoomStatus {
  WAITING = 'WAITING',
  DISMISSED = 'DISMISSED',
  PRESENTING = 'PRESENTING',
  PICTURING = 'PICTURING',
  GEO_GUESSING = 'GEO_GUESSING',
  WORDLING = 'WORDLING',
  GAMING = 'GAMING',
  NON_EXIST = 'NON_EXIST',
  HANGINGMAN = "HANGINGMAN"
}
